fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

check:
    resource: "@CheckPageBundle/Controller"
    type: annotation
    prefix: /check

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    options: { i18n: false }
    prefix: /